export const GET_FEATURED_DATA_R = "GET_FEATURED_DATA_R";
export const GET_FEATURED_DATA_S = "GET_FEATURED_DATA_S";
export const GET_FEATURED_DATA_F = "GET_FEATURED_DATA_F";
export const GET_WOMENS_DATA_S = "GET_WOMENS_DATA_S";
export const GET_SHOES_DATA_S = "GET_SHOES_DATA_S";

export const GET_SUBSCRIBED_R = "GET_SUBSCRIBED_R";
export const GET_SUBSCRIBED_S = "GET_SUBSCRIBED_S";
export const GET_SUBSCRIBED_F = "GET_SUBSCRIBED_F";
